### ISSUE TITLE
The latency on the snapdragon 8 gen 1 is almost the same before and after re-parameterized

### ISSUE THREAD

**Issue by neptune4year** [ChengpengChen/RepGhost#6]
Thanks very much for sharing this excellent work.
Our whole model is an U-net style model with RepGhost as the backbone, and we convert it to ONNX and then convert it to MNN.
But we found that the latency is almost the same before re-parameterized (15ms) and after re-parameterized (13ms)， would it be correct?

**Comment by ChengpengChen** [comment]
Hi, neptune4year,

The speedup (13.3%) is to be expected, because the re-parameterization structure (only one BN for dw conv) of our network is much simpler, compared to those of RepVGG and MobileOne.

Beside, thanks for extending our network to a U-Net style. Please feel free to contact me, If you have any questions about its application.

**Comment by neptune4year** [comment]
Thanks a lot, I got it.
